i18n:
  activeIncidentSummary: 在DATE 打开，有 POSTS 个帖子
  activeIncidents: 活动事件
  allSystemsOperational: 所有系统都可以正常运行
  averageResponseTime: 平均响应时间:TIMEms
  averageResponseTimeTitle: 平均响应时间
  completeOutage: 🟥 全部停机
  degraded: 🟨 运行缓慢
  degradedPerformance: 🟨 性能降低
  down: 🟥 停机
  duration: 持续时间
  durationMin: $DURATION 分钟
  errorHome: 转到主页
  errorIntro: 尝试获取最新状态详细信息时出错。
  errorText: 您可以稍后再试。
  errorTitle: 发生错误
  footer: K5保留所有权利。 Copyright © 2025 K5. All Rights Reserved.
  history: 历史
  incidentBack: ← 返回所有事件
  incidentClosedAt: 结束于
  incidentCommentSummary: 由 AUTHOR 在DATE 发布
  incidentCompleted: 已完成
  incidentDetails: 事件详细信息
  incidentFixed: 已修复
  incidentOngoing: 正在进行
  incidentOpenedAt: 开始于
  incidentReport: '事件 #NUMBER 报告 →'
  incidentScheduled: 已预定
  incidentSubscribe: 订阅更新
  incidentTitle: 事件NUMBER 的详细信息
  incidentViewOnGitHub: 在 GitHub 上查看
  liveStatus: 实时状态
  liveStatusHtmlComment: <！ -实时状态- >
  loading: 加载中
  ms: 毫秒
  navGitHub: GitHub
  overallUptime: 总体正常运行时间： UPTIME
  overallUptimeTitle: 总体正常运行时间
  partialOutage: 🟧 部分停机
  pastIncidents: 过去的事件
  pastIncidentsResolved: POSTS 个问题在MINUTES 分钟内得到解决
  pastScheduledMaintenance: 过去的预定维护
  rateLimitExceededCopyPastePAT: 复制并粘贴您的令牌
  rateLimitExceededErrorFix: 您可以再等一个小时，您的 IP 地址限制将恢复。或者，您可以添加您的 GitHub 个人访问令牌，这将为您提供每小时额外
    5,000 个请求。
  rateLimitExceededErrorHowCanFix: 我该如何解决？
  rateLimitExceededGeneratePAT: 了解如何生成个人访问令牌
  rateLimitExceededGitHubPAT: GitHub 个人访问令牌
  rateLimitExceededHasSet: 您有一个个人访问令牌集。
  rateLimitExceededIntro: 您已超过一小时内可以执行的请求数，因此您必须等待才能再次访问此网站。或者，您可以添加 GitHub 个人访问令牌以继续使用本网站。
  rateLimitExceededRemoveToken: 删除令牌
  rateLimitExceededSaveToken: 保存令牌
  rateLimitExceededTitle: 超出速率限制
  rateLimitExceededWhatDoesErrorMean: 这个错误是什么意思？本网站使用 GitHub API 访问有关我们网站状态的实时数据。默认情况下，GitHub
    允许每个 IP 地址每小时 60 个请求，您已经消耗了这些请求。
  responseTime: 响应时间
  responseTimeDay: 24 小时响应时间
  responseTimeGraphAlt: 响应时间图像
  responseTimeMonth: 30天的正常运行时间
  responseTimeMs: 响应时间（毫秒）
  responseTimeWeek: 7 天正常运行时间
  responseTimeYear: 1年的正常运行时间
  scheduledMaintenance: 定期维护
  scheduledMaintenanceSummaryStarted: 从 DATE 开始，持续DURATION 分钟
  scheduledMaintenanceSummaryStarts: 从 DATE 开始，持续DURATION 分钟
  sevelDayResponseTime: 7 天响应时间
  startedAt: 开始在
  startsAt: 开始于
  status: 状态
  up: 🟩 正常运行
  uptime: 正常运行时间
  uptimeDay: 24 小时正常运行时间
  uptimeMonth: 30天的正常运行时间
  uptimeWeek: 7 天正常运行时间
  uptimeYear: 1年的正常运行时间
  url: 链接
owner: Limkon
repo: upptime
sites:
- name: jxio.nyc.mn
  url: https://jxio.nyc.mn/
- name: veco.nyc.mn
  url: https://veco.nyc.mn/
- name: zoot.nyc.mn
  url: https://zoot.nyc.mn/
- name: xisu.nyc.mn
  url: https://xisu.nyc.mn/
- name: stdu.nyc.mn
  url: https://stdu.nyc.mn/
- name: www.google.com.tw
  url: https://www.google.com.tw/
status-website:
  cname: stdu.nyc.mn
  introMessage: This is a sample status page which uses **real-time** data from our
    [GitHub repository](https://). No server required — just GitHub Actions, Issues,
    and Pages. [**Get your own for free**](https://)
  introTitle: '**Upptime** is the open-source uptime monitor and status page, powered
    entirely by GitHub.'
  logoUrl: https://raw.githubusercontent.com/Limkon/upptime/refs/heads/master/assets/icon.svg
  name: Upptime
  navbar:
  - href: /
    title: Status
  - href: https://github.com/$OWNER/$REPO
    title: GitHub
